name    'frib-epics_gateway'
version '0.1.0'
source 'https://stash.nscl.msu.edu/scm/deploy/puppet_module_epics_gateway.git'
author 'konrad'
license 'MIT License (Expat)'
summary 'Puppet module for EPICS Channel Access Gateway'
description 'Module for installation and configuration of EPICS Channel Access Gateway.'
project_page 'https://stash.nscl.msu.edu/projects/DEPLOY/repos/puppet_module_epics_gateway'