#! /bin/sh
### BEGIN INIT INFO
# Provides:          cagateway-<%= @name %>
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start EPICS PV gateway daemon in procServ
# Description:       Enable EPICS PV Gateway, which allows access to
#                    PVs in other subnets from 192.168.2.xxx.
### END INIT INFO

NAME=$(basename $0)
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
PROCSERV=/usr/bin/procServ
GATEWAY=/usr/bin/cagateway
USER=cagateway

test -x $PROCSERV || exit 0
test -x $GATEWAY || exit 0

set -e

# default values
SERVER_PORT=5064
CLIENT_PORT=5064
PREFIX="gateway2"

. /lib/lsb/init-functions

if test -f /etc/default/$NAME; then
    . /etc/default/$NAME
fi

if [ -n "$COMMAND_FILE" ]
then
  COMMAND_FILE_OPT="-command $COMMAND_FILE"
else
  COMMAND_FILE_OPT=''
fi

ARCHIVE_LOWERCASE=`echo $ARCHIVE | tr '[:upper:]' '[:lower:]'`
if [ "$ARCHIVE_LOWERCASE" = "true" ] || [ "$ARCHIVE_LOWERCASE" = "yes" ]
then
  ARCHIVE_OPT='-archive'
else
  ARCHIVE_OPT=''
fi

NO_CACHE_LOWERCASE=`echo $NO_CACHE | tr '[:upper:]' '[:lower:]'`
if [ "$NO_CACHE_LOWERCASE" = "true" ] || [ "$NO_CACHE_LOWERCASE" = "yes" ]
then
  NO_CACHE_OPT='-no_cache'
else
  NO_CACHE_OPT=''
fi

if [ -n "$CAPUTLOG_HOST" ] && [ -n "$CAPUTLOG_PORT" ]
then
  CAPUTLOG_OPT="-caputlog ${CAPUTLOG_HOST}:$CAPUTLOG_PORT"
else
  CAPUTLOG_OPT=''
fi

GATEWAY_OPTS="-sip $SERVER_IP -cip $CLIENT_IP -signore $IGNORE_IPS -sport $SERVER_PORT -cport $CLIENT_PORT -home $HOME_DIR -pvlist $PV_LIST_FILE -access $ACCESS_SECURITY_FILE $COMMAND_FILE_OPT $ARCHIVE_OPT $NO_CACHE_OPT $CAPUTLOG_OPT -log $LOG_FILE -prefix $PREFIX $PARAMS"
PROCSERV_OPTS="--quiet --pidfile /var/run/${NAME}/pid"

check_status() {
  if [ "$1" = "-q" ];then
    status_of_proc -p "$PID" "procServ" "$IOC" 2>&1 >/dev/null
  else
    status_of_proc -p "$PID" "procServ" "$IOC"
  fi
  return $?
}

case "$1" in
  start)
        echo -n "Starting $DESC: "
        start-stop-daemon --start --pidfile /var/run/${NAME}/pid --chuid "$USER" --exec $PROCSERV -- $PROCSERV_OPTS $PROCSERV_PORT $GATEWAY $GATEWAY_OPTS
        echo "$NAME."
        ;;
  stop)
        echo -n "Stopping $DESC: "
        start-stop-daemon --stop --pidfile /var/run/${NAME}/pid --user "$USER"--exec $PROCSERV
        rm -f /var/run/$NAME.pid
        echo "$NAME."
        ;;
  status)
        echo -n "Status of gateway $NAME : "
        check_status
        exit $?
        ;;
  restart|force-reload)
        echo -n "Restarting $DESC: "
        start-stop-daemon --stop --pidfile /var/run/${NAME}/pid --user "$USER" --exec $PROCSERV
        rm -f /var/run/$NAME.pid
        sleep 1
        start-stop-daemon --start --pidfile /var/run/${NAME}/pid --chuid "$USER" --exec $PROCSERV -- $PROCSERV_OPTS $PROCSERV_PORT $GATEWAY $GATEWAY_OPTS
        echo "$NAME."
        ;;
  *)
        N=/etc/init.d/$NAME
        # echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
        echo "Usage: $N {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0